# Generated by Django 4.2.4 on 2023-08-03 16:04

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('location', models.TextField()),
                ('user', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Moniter',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('on_duration', models.DateTimeField()),
                ('off_duration', models.DateTimeField()),
                ('usage', models.DecimalField(decimal_places=2, max_digits=10)),
                ('user', models.TextField()),
                ('sensor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sensors.sensor')),
            ],
        ),
    ]
