# Generated by Django 4.2.4 on 2023-08-05 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moniter',
            name='off_duration',
            field=models.DateTimeField(null=True),
        ),
    ]
