# Generated by Django 4.2.4 on 2023-08-06 08:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0003_moniter_status_alter_moniter_usage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moniter',
            name='on_duration',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
